name: Bug Report
description: Report a reproducible bug  unexpected behavior
title: "[Bug] | "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: input
    id: invite_code
    attributes:
      label: Discord Invite Code
      description: The invite code used in the widget (if applicable)
      placeholder: GaczkwfgV9
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue clearly.
      placeholder: The widget does not render the banner correctly...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: The banner should display with proper clipping...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if applicable)
      description: Paste screenshots or rendered SVG output here.
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Where is this being rendered? (GitHub, website, local)
      placeholder: GitHub README
    validations:
      required: false
