name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] | "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve the widget? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: I want support for animated banners...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      placeholder: Add GIF banner support with fallback frame extraction...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: Using static fallback images...
    validations:
      required: false
